POST http://localhost:5055/auth/
Content-Type: application/json

{
  "username": "John",
  "password": "test"
}

###

POST http://localhost:5055/auth/
Content-Type: application/json

{
  "username": "Admin",
  "password": "test"
}

###
PUT http://localhost:5055/auth/
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjY4MjQzNzE1fQ.jrQfZBBhSj5TRCeo3GlLqSM3bsDK60sWkKTqrldWCP8"
}

###