GET http://localhost:5055/users/
Accept: application/json

###

POST http://localhost:5055/users/
Content-Type: application/json

{
  "username": "John",
  "password": "test",
  "role": "user"
}

###
